image: rikorose/gcc-cmake:latest

before_script:
    - apt-get update --yes
    - apt-get install --yes doxygen

stages:
    - build
    - test

build:
    stage: build
    variables:
        CC: gcc
        CXX: g++
    script:
        - cmake -DBUILD_TESTING=ON -Bbuild -H.
        - cmake --build build
    artifacts:
        untracked: true

test:
    stage: test
    script:
        - make -Cbuild test
    dependencies:
        - build

pages:
    script:
        - mv build/html/ public/
    artifacts:
        paths:
            - public
    only:
        - master
    dependencies:
        - build
